# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c489b3a24d6d0da697bb5f15002fd81143a0118864036ea16d752a86d62cdb9ab4ccc4022d5674bb07b217f2db393927e322279761b05b65a2d06a358f453f

test:
  secret_key_base: 9ae0d1522d8360439fc7e899fb436e8198358d372333b33997b93ee6c8623f511638d79f56d1b6d5ba3cf5b83bd7f843770e493a1318bf94295f7b0d4c0716c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
